@base_address = http://localhost:8080
GET {{base_address}}/products
###
POST {{base_address}}/orders
Content-Type: application/json

{
  "productId": "f1122ce7-4f70-46ad-8345-01bfb60beb21",
  "quantity": 10
}
###
POST {{base_address}}/orders
Content-Type: application/json

{
  "productId": "f1122ce7-4f70-46ad-8345-01bfb60beb21",
  "quantity": 10,
  "recipientName": "molodoy chelovek",
  "phone": "79308533270",
  "addressLine1": "ylica pushkina",
  "addressLine2": "dom kolotyshkina",
  "city": "Moskva Gorod123",
  "region": "md",
  "postalCode": "123",
  "countryCode": "zz"
}
###
GET {{base_address}}/products/f1122ce7-4f70-46ad-8345-01bfb60beb21/events
###
POST {{base_address}}/orders/cancel
Content-Type: application/json

{
  "productId": "f1122ce7-4f70-46ad-8345-01bfb60beb21",
  "quantity": 50
}

###
POST {{base_address}}/products/restock
Content-Type: application/json

{
  "productId": "f1122ce7-4f70-46ad-8345-01bfb60beb21",
  "quantity": 10
}